version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: psc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: psc_db
      MYSQL_USER: pscuser
      MYSQL_PASSWORD: pscpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
